name: karma_quest
description: A gamified task manager based on karmic principles.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  provider: ^6.1.2
  http: ^1.2.0

flutter:
  uses-material-design: true
