// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To configure this file with your own Firebase projects, run:
///   `flutterfire configure`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // PLACEHOLDER Firebase configuration options.
  // Replace these with your actual Firebase project settings.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_PLACEHOLDER_API_KEY_WEB',
    appId: '1:1234567890:web:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'cosmovedic-app',
    authDomain: 'cosmovedic-app.firebaseapp.com',
    storageBucket: 'cosmovedic-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_PLACEHOLDER_API_KEY_ANDROID',
    appId: '1:1234567890:android:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'cosmovedic-app',
    storageBucket: 'cosmovedic-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_PLACEHOLDER_API_KEY_IOS',
    appId: '1:1234567890:ios:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'cosmovedic-app',
    storageBucket: 'cosmovedic-app.appspot.com',
    iosBundleId: 'com.cosmovedic.cosmovedic',
  );
}
