with open('index.html', 'rb') as f:
    content = f.read()

# 1. Fix loadCloudConfig to safely handle null DOM elements db-url and db-key
old_loadCloudConfig = (
    b"function loadCloudConfig() {\r\n"
    b"const url = localStorage.getItem('supabase_url') || 'https://rnunibjmmowhaxsytthf.supabase.co';\r\n"
    b"const key = localStorage.getItem('supabase_key') || 'sb_publishable_jjYnowJojZtzDjqEmVXACg_C7J1PGlq';\r\n"
    b"document.getElementById('db-url').value = url;\r\n"
    b"document.getElementById('db-key').value = key;\r\n"
    b"try {\r\n"
    b"supabaseClient = supabase.createClient(url, key);\r\n"
    b"document.getElementById('cloud-status').innerText = \" Connected to Supabase Cloud Database\";\r\n"
    b"document.getElementById('cloud-status').style.color = \"#E8C879\";\r\n"
    b"} catch (e) {\r\n"
    b"document.getElementById('cloud-status').innerText = \" Failed to initialize client\";\r\n"
    b"document.getElementById('cloud-status').style.color = \"#ff6b6b\";\r\n"
    b"}\r\n"
    b"}"
)

new_loadCloudConfig = (
    b"function loadCloudConfig() {\r\n"
    b"const url = localStorage.getItem('supabase_url') || 'https://rnunibjmmowhaxsytthf.supabase.co';\r\n"
    b"const key = localStorage.getItem('supabase_key') || 'sb_publishable_jjYnowJojZtzDjqEmVXACg_C7J1PGlq';\r\n"
    b"const urlEl = document.getElementById('db-url');\r\n"
    b"const keyEl = document.getElementById('db-key');\r\n"
    b"if (urlEl) urlEl.value = url;\r\n"
    b"if (keyEl) keyEl.value = key;\r\n"
    b"try {\r\n"
    b"if (typeof supabase !== 'undefined' && supabase.createClient) {\r\n"
    b"supabaseClient = supabase.createClient(url, key);\r\n"
    b"const statusEl = document.getElementById('cloud-status');\r\n"
    b"if (statusEl) {\r\n"
    b"statusEl.innerText = \" Connected to Supabase Cloud Database\";\r\n"
    b"statusEl.style.color = \"#E8C879\";\r\n"
    b"}\r\n"
    b"}\r\n"
    b"} catch (e) {\r\n"
    b"const statusEl = document.getElementById('cloud-status');\r\n"
    b"if (statusEl) {\r\n"
    b"statusEl.innerText = \" Failed to initialize client\";\r\n"
    b"statusEl.style.color = \"#ff6b6b\";\r\n"
    b"}\r\n"
    b"}\r\n"
    b"}"
)

# 2. Fix dismissSplashScreen with robust fail-safe layout routing
old_dismissSplash = (
    b"function dismissSplashScreen() {\r\n"
    b"const splash = document.getElementById('splash-screen');\r\n"
    b"const onboarding = document.getElementById('onboarding-screen');\r\n"
    b"const appLayout = document.getElementById('app-layout');\r\n"
    b"\r\n"
    b"// Check if URL contains Google OAuth Callback tokens/code\r\n"
    b"const hash = window.location.hash;\r\n"
    b"const search = window.location.search;\r\n"
    b"const isOAuthRedirect = (hash && (hash.includes('access_token=') || hash.includes('type='))) || (search && search.includes('code='));\r\n"
    b"\r\n"
    b"if (isOAuthRedirect) {\r\n"
    b"if (splash) splash.style.display = 'none';\r\n"
    b"return; // Allow handleOAuthCallback to manage screen routing!\r\n"
    b"}\r\n"
    b"\r\n"
    b"if (splash) {\r\n"
    b"splash.style.opacity = '0';\r\n"
    b"setTimeout(async () => {\r\n"
    b"splash.style.display = 'none';\r\n"
    b"const isAuthFlag = localStorage.getItem('user_authenticated') === 'true';\r\n"
    b"\r\n"
    b"// RULE 1: If user manually logged out, ALWAYS REQUIRE SIGN IN!\r\n"
    b"if (!isAuthFlag) {\r\n"
    b"if (appLayout) appLayout.style.display = 'none';\r\n"
    b"if (onboarding) onboarding.style.display = 'flex';\r\n"
    b"showOnboardingStep('path');\r\n"
    b"return;\r\n"
    b"}\r\n"
    b"\r\n"
    b"// RULE 2: Validate backend user session with Supabase Cloud\r\n"
    b"let validBackendUser = false;\r\n"
    b"let currentUserId = null;\r\n"
    b"if (supabaseClient) {\r\n"
    b"try {\r\n"
    b"const { data: { user }, error } = await supabaseClient.auth.getUser();\r\n"
    b"if (user && !error) {\r\n"
    b"validBackendUser = true;\r\n"
    b"currentUserId = user.id;\r\n"
    b"}\r\n"
    b"} catch (err) {\r\n"
    b"console.log(\"Supabase backend auth check error:\", err);\r\n"
    b"}\r\n"
    b"}\r\n"
    b"\r\n"
    b"// STRICT RULE: ALWAYS restore from Supabase cloud when user is authenticated.\r\n"
    b"// localStorage is NOT a routing source of truth \xe2\x80\x94 it may be stale or cleared on logout.\r\n"
    b"let cloudProfileExists = false;\r\n"
    b"if (validBackendUser && currentUserId) {\r\n"
    b"try {\r\n"
    b"const restored = await restoreProfileFromCloud(currentUserId);\r\n"
    b"cloudProfileExists = restored;\r\n"
    b"} catch(e) {\r\n"
    b"// Fallback: if cloud fetch fails, check local cache only as last resort\r\n"
    b"cloudProfileExists = !!(localStorage.getItem('user_name') && localStorage.getItem('user_dob'));\r\n"
    b"}\r\n"
    b"}\r\n"
    b"\r\n"
    b"// RULE 3: If user was DELETED from backend database, wipe local cache & require sign in!\r\n"
    b"if (supabaseClient && !validBackendUser && isAuthFlag) {\r\n"
    b"localStorage.clear();\r\n"
    b"sessionStorage.clear();\r\n"
    b"if (appLayout) appLayout.style.display = 'none';\r\n"
    b"if (onboarding) onboarding.style.display = 'flex';\r\n"
    b"showOnboardingStep('path');\r\n"
    b"return;\r\n"
    b"}\r\n"
    b"\r\n"
    b"// RULE 4 (STRICT): If authenticated AND Supabase profile EXISTS (or local profile exists) \xe2\x86\x92 dashboard always.\r\n"
    b"// If authenticated BUT no Supabase profile & no local profile \xe2\x86\x92 new user \xe2\x86\x92 onboarding path.\r\n"
    b"if (validBackendUser) {\r\n"
    b"const hasLocalProfile = !!(localStorage.getItem('user_name') && localStorage.getItem('user_dob'));\r\n"
    b"if (cloudProfileExists || hasLocalProfile) {\r\n"
    b"if (onboarding) onboarding.style.display = 'none';\r\n"
    b"if (appLayout) appLayout.style.display = 'block';\r\n"
    b"if (typeof initApp === 'function') initApp();\r\n"
    b"} else {\r\n"
    b"// Genuinely new user \xe2\x80\x94 no profile row in DB yet and no local cache\r\n"
    b"if (appLayout) appLayout.style.display = 'none';\r\n"
    b"if (onboarding) onboarding.style.display = 'flex';\r\n"
    b"showOnboardingStep('select-path');\r\n"
    b"}\r\n"
    b"} else {\r\n"
    b"// No valid backend session \xe2\x86\x92 show auth entrance screen\r\n"
    b"if (appLayout) appLayout.style.display = 'none';\r\n"
    b"if (onboarding) onboarding.style.display = 'flex';\r\n"
    b"showOnboardingStep('path');\r\n"
    b"}\r\n"
    b"}, 600);\r\n"
    b"}\r\n"
    b"}"
)

new_dismissSplash = (
    b"function dismissSplashScreen() {\r\n"
    b"const splash = document.getElementById('splash-screen');\r\n"
    b"const onboarding = document.getElementById('onboarding-screen');\r\n"
    b"const appLayout = document.getElementById('app-layout');\r\n"
    b"\r\n"
    b"// Ensure Supabase client is initialized if not yet done\r\n"
    b"if (!supabaseClient && typeof loadCloudConfig === 'function') {\r\n"
    b"try { loadCloudConfig(); } catch(e) {}\r\n"
    b"}\r\n"
    b"\r\n"
    b"// Check if URL contains Google OAuth Callback tokens/code\r\n"
    b"const hash = window.location.hash;\r\n"
    b"const search = window.location.search;\r\n"
    b"const isOAuthRedirect = (hash && (hash.includes('access_token=') || hash.includes('type='))) || (search && search.includes('code='));\r\n"
    b"\r\n"
    b"if (isOAuthRedirect) {\r\n"
    b"if (splash) splash.style.display = 'none';\r\n"
    b"return; // Allow handleOAuthCallback to manage screen routing!\r\n"
    b"}\r\n"
    b"\r\n"
    b"if (splash) {\r\n"
    b"splash.style.opacity = '0';\r\n"
    b"setTimeout(async () => {\r\n"
    b"splash.style.display = 'none';\r\n"
    b"try {\r\n"
    b"const isAuthFlag = localStorage.getItem('user_authenticated') === 'true';\r\n"
    b"const hasLocalProfile = !!(localStorage.getItem('user_name') && localStorage.getItem('user_dob'));\r\n"
    b"\r\n"
    b"let validBackendUser = false;\r\n"
    b"let currentUserId = null;\r\n"
    b"if (supabaseClient && supabaseClient.auth) {\r\n"
    b"try {\r\n"
    b"const { data: { user }, error } = await supabaseClient.auth.getUser();\r\n"
    b"if (user && !error) {\r\n"
    b"validBackendUser = true;\r\n"
    b"currentUserId = user.id;\r\n"
    b"}\r\n"
    b"} catch (err) {\r\n"
    b"console.log(\"Supabase backend auth check error:\", err);\r\n"
    b"}\r\n"
    b"}\r\n"
    b"\r\n"
    b"let cloudProfileExists = false;\r\n"
    b"if (validBackendUser && currentUserId) {\r\n"
    b"try {\r\n"
    b"cloudProfileExists = await restoreProfileFromCloud(currentUserId);\r\n"
    b"} catch(e) {\r\n"
    b"cloudProfileExists = hasLocalProfile;\r\n"
    b"}\r\n"
    b"}\r\n"
    b"\r\n"
    b"// If user has active auth session OR cloud profile OR local profile -> Dashboard\r\n"
    b"if (isAuthFlag || validBackendUser || cloudProfileExists || hasLocalProfile) {\r\n"
    b"if (onboarding) onboarding.style.display = 'none';\r\n"
    b"if (appLayout) appLayout.style.display = 'block';\r\n"
    b"if (typeof initApp === 'function') initApp();\r\n"
    b"} else {\r\n"
    b"// New unauthenticated guest -> Onboarding Auth gateway\r\n"
    b"if (appLayout) appLayout.style.display = 'none';\r\n"
    b"if (onboarding) onboarding.style.display = 'flex';\r\n"
    b"showOnboardingStep('path');\r\n"
    b"}\r\n"
    b"} catch(err) {\r\n"
    b"console.error('[Astro AI] Splash dismissal error:', err);\r\n"
    b"const hasLocalProfile = !!(localStorage.getItem('user_name') && localStorage.getItem('user_dob'));\r\n"
    b"if (hasLocalProfile) {\r\n"
    b"if (onboarding) onboarding.style.display = 'none';\r\n"
    b"if (appLayout) appLayout.style.display = 'block';\r\n"
    b"if (typeof initApp === 'function') initApp();\r\n"
    b"} else {\r\n"
    b"if (appLayout) appLayout.style.display = 'none';\r\n"
    b"if (onboarding) onboarding.style.display = 'flex';\r\n"
    b"showOnboardingStep('path');\r\n"
    b"}\r\n"
    b"}\r\n"
    b"}, 600);\r\n"
    b"}\r\n"
    b"}"
)

# Apply fixes
if old_loadCloudConfig in content:
    content = content.replace(old_loadCloudConfig, new_loadCloudConfig, 1)
    print("SUCCESS: Fixed loadCloudConfig null element handling")
else:
    print("WARNING: Could not find old_loadCloudConfig")

if old_dismissSplash in content:
    content = content.replace(old_dismissSplash, new_dismissSplash, 1)
    print("SUCCESS: Updated dismissSplashScreen with fail-safe layout routing")
else:
    print("WARNING: Could not find old_dismissSplash")

with open('index.html', 'wb') as f:
    f.write(content)

print("File written.")
